name: build
on: [push]
jobs:
  # Set up node, install dependencies, then run `npm run build`.
  # The three built output files in `dist` stand as artifacts:
  # - `miniweb.js`
  # - `miniweb.js.map`
  # - `miniweb.d.ts`
  # but not any of the other cruft in `dist`.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: miniweb.js
          path: dist/miniweb.js
      - uses: actions/upload-artifact@v4
        with:
          name: miniweb.js.map
          path: dist/miniweb.js.map
      - uses: actions/upload-artifact@v4
        with:
          name: miniweb.d.ts
          path: dist/miniweb.d.ts
